# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Megan L. Lavengood
author: Dr. Megan L. Lavengood
email: mlavengo@gmu.edu
description: >- # this means to ignore newlines until "baseurl:"
    Personal website for Megan Lavengood, music theorist.

domain: https://meganlavengood.com
url: https://meganlavengood.com
baseurl: "" # the subpath of your site, e.g. /blog
# repository: meganlavengood/instruments-class
github_username: meganlavengood

# Build settings

# destination: docs/

# theme: minima
plugins:
    - jekyll-feed
    - jekyll-remote-theme
    - jekyll-scholar
    - jekyll-toc
    - jekyll-spaceship
    # - jekyll-target-blank
defaults:
    - scope:
          path: ""
      values:
          toc: true

show_excerpts: true

kramdown:
    input: Kramdown

# Jekyll-TOC
toc:
    min_level: 2
    max_level: 2
    ordered_list: false
    list_id: toc
    list_class: section-nav
    sublist_class: "toc-sublist"
    item_class: toc-entry
    item_prefix: toc-

scholar:
    bibliography: instruments-class.bib
    style: chicago-author-date
    bibtex_filters:
        - latex
        - HtmlLinks
        - DOILinks
    sort_by: author

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: /:year/:month/:day/:title

future: true
